apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
spec:
  selector:
    app: {{.Values.name }}
  type:
  ports:
    - protocol: TCP
      port: {{ .Values.services.port }} 
      targetPort: {{ .Values.services.targetPort }} 
